"""Per-format importers. Each returns canonical markdown.

Format detection is shallow (extension + MIME). Block IDs are generated by
`block_ids.py` from the resulting markdown, so importers only need to emit
clean markdown — they don't worry about IDs.
"""
from __future__ import annotations

import io
import logging
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class ImportResult:
    markdown: str
    backend: str
    metadata: dict


def import_txt(raw: bytes) -> ImportResult:
    text = raw.decode("utf-8", errors="replace")
    return ImportResult(markdown=text.strip() + "\n", backend="identity", metadata={})


def import_md(raw: bytes) -> ImportResult:
    text = raw.decode("utf-8", errors="replace")
    return ImportResult(markdown=text.strip() + "\n", backend="identity", metadata={})


def import_html(raw: bytes) -> ImportResult:
    import html2text

    h = html2text.HTML2Text()
    h.body_width = 0  # don't wrap lines
    h.ignore_links = False
    h.unicode_snob = True
    h.bypass_tables = False
    text = raw.decode("utf-8", errors="replace")
    md = h.handle(text)
    return ImportResult(markdown=md.strip() + "\n", backend="html2text", metadata={})


def import_pdf(raw: bytes) -> ImportResult:
    import pymupdf4llm
    import pymupdf

    with pymupdf.open(stream=raw, filetype="pdf") as doc:
        md = pymupdf4llm.to_markdown(doc)
        pages = doc.page_count
        title = doc.metadata.get("title") if doc.metadata else None

    return ImportResult(
        markdown=md.strip() + "\n",
        backend="pymupdf4llm",
        metadata={"pages": pages, "title": title} if title else {"pages": pages},
    )


def import_docx(raw: bytes) -> ImportResult:
    import mammoth
    import html2text

    result = mammoth.convert_to_html(io.BytesIO(raw))
    html = result.value
    h = html2text.HTML2Text()
    h.body_width = 0
    h.ignore_links = False
    h.unicode_snob = True
    md = h.handle(html)
    return ImportResult(markdown=md.strip() + "\n", backend="mammoth+html2text", metadata={})


def dispatch(filename: str, mime: str | None, raw: bytes) -> ImportResult:
    ext = (filename.rsplit(".", 1)[-1] or "").lower() if "." in filename else ""
    m = (mime or "").lower()

    # ext-first, fall back to mime hints
    if ext == "txt" or m.startswith("text/plain"):
        return import_txt(raw)
    if ext in ("md", "markdown") or m == "text/markdown":
        return import_md(raw)
    if ext in ("htm", "html") or m.startswith("text/html"):
        return import_html(raw)
    if ext == "pdf" or m == "application/pdf":
        return import_pdf(raw)
    if ext == "docx" or m == "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
        return import_docx(raw)
    raise ValueError(f"unsupported file type: ext={ext!r} mime={mime!r}")


SUPPORTED_IMPORT = [
    {"ext": "pdf", "mime": "application/pdf", "structure": "high"},
    {"ext": "docx", "mime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "structure": "high"},
    {"ext": "html", "mime": "text/html", "structure": "medium"},
    {"ext": "md", "mime": "text/markdown", "structure": "pass-through"},
    {"ext": "txt", "mime": "text/plain", "structure": "low"},
]
